In [1]:
import numpy as np

In [2]:
# Display the installed numpy version

print('The installed numpy version is:', np.__version__)

The installed numpy version is: 1.24.3


--------------------------------------------------------
### **Generate a numpy array, filling with zeros**

The default data type in the numpy array is platform dependent, but we can specify the data type with parameter **dtype**

In [3]:
# Using np.zeros() to generate zeros array
zeros_array = np.zeros(5)

# Show the content of zeros_array explicitly
print(zeros_array)

# Check the data type of zeros_array
print('\nThe data type of zero_array is:', zeros_array.dtype)

[0. 0. 0. 0. 0.]

The data type of zero_array is: float64


In [4]:
# Specifying the data typf as int8 when generate a zeros array
zero_array_int = np.zeros(5, dtype=np.int8)

# Show the content of zeros_array explicitly
print(zero_array_int)

# Check the data type of zero_array_int
print('\nThe data type of zero_array is:', zero_array_int.dtype)

[0 0 0 0 0]

The data type of zero_array is: int8


-------------------------------------------
### **Generate a numpy array, filling with ones**

#### **Generate a numpy with integer numbers, filling with ones**

In [5]:
# Using np.ones() to generate an array filling with integer ones
ones_array = np.ones([3,3], dtype=np.int8)

# Display the content of ones_array
print(ones_array)

# Check the data type of ones_array
print('\nThe data type of ones_array is:',ones_array.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]]

The data type of ones_array is: int8


#### **Generate a numpy with float numbers, filling with ones**

In [6]:
# Using np.ones() to generate an array filling with float ones
ones_array = np.ones([3,3], dtype=np.float16)

# Display the content of ones_array
print(ones_array)

# Check the data type of ones_array
print('\nThe data type of ones_array is:',ones_array.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

The data type of ones_array is: float16


------------------------------------
### **Generate a matrix with the same shape of a given matrix, filling with ones or zeros**

In [7]:
X = np.arange(3, dtype=np.int8)

# Using np.ones_like() to generate an ones array that has the same shape like X
np.ones_like(X)

array([1, 1, 1], dtype=int8)

In [8]:
# Using np.zeros_like() to generate a zeros array that has the same shape like X
np.zeros_like(X)

array([0, 0, 0], dtype=int8)

#### **Generate a 5x5 matrix, filling with fives**

In [9]:
np.ones([5,5], dtype=np.int8)*5

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]], dtype=int8)

-------------------------------------------------------------
### **Generate a numpy array that ranges from 1 to 20**

In [10]:
# Using np.arange() to generate an array within a given range [x1,x2], x2 will not be included
a = np.arange(1,20)

a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

-----------------------------
### **Generate a matrix with ones on the diagonol**

In [11]:
# Using np.eye() to generate a diagonol matrix
np.eye(3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [12]:
# Using np.eye() to generate a diagonol matrix with 5 on the diagonol
np.eye(4, dtype=np.int8)*5

array([[5, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 5]], dtype=int8)

----------------------------
### **Generate random numbers**

**np.random.randint(low, high=None, size=None, dtype=int)**  

numpy random module used to generat random numbers, and has following parameters:  
**low**: The lowest (inclusive) integer to be drawn from the distribution.  
**high**: The highest (exclusive) integer to be drawn from the distribution. If omitted, the range is assumed to be [0, low).  
**size**: The number of random integers to generate. If size is None, a single random integer is returned. If size is an integer, it specifies the number of integers to generate.  
**dtype**: Data type of the result. If not specified, it defaults to the data type of the array created.

In [13]:
np.random.randint(10, size=3)

array([6, 0, 4])

In [14]:
np.random.randint(1,15,size=[2,3])

array([[ 2, 12,  7],
       [ 1, 10, 10]])

**np.random.randn(d0,d1,...dn)**

generate random numbers from a **standard normal distribution**(mean=0, standard deviation=1). Its parameters d0, d1,...dn are the dimenstions of the output. If it is not given, a single random number will be generated.

In [15]:
random_sample = np.random.randn()
random_sample

-0.3491136471785266

In [16]:
random_array = np.random.randn(3)
random_array

array([-1.28752314, -1.47489131,  0.18549446])

In [17]:
random_matrix = np.random.randn(2,4)
print(random_matrix)

[[-0.4441308  -0.39649154 -0.23538467  0.23235012]
 [-0.58042198  0.63417176  0.24875782  0.01981706]]
